export interface MediaItem {
  id: string;
  name: string;
  category: "National" | "Regional" | "Business" | "Legal" | "Immigration";
  title: string;
  date?: string;
  summary?: string;
  link: string;
  featured?: boolean;
  logoText?: string;
}

export const FEATURED_ARTICLES: MediaItem[] = [
  {
    id: "tribune-india",
    name: "The Tribune",
    category: "National",
    title: "Immigration Experts Highlight Fraud Risks Linked to Fake Work Permit Offers in India",
    date: "14 Aug 2024",
    summary: "Every week, families from small towns across Punjab, Haryana, Uttar Pradesh, Himachal Pradesh and several other states make one of the biggest financial decisions of their lives — navigating fake work permit risks with guidance from expert immigration advocates.",
    link: "https://www.tribuneindia.com/partner-exclusives/immigration-experts-highlight-fraud-risks-linked-to-fake-work-permit-offers-in-india/",
    featured: true,
    logoText: "The Tribune",
  },
  {
    id: "ahmedabad-mirror",
    name: "Ahmedabad Mirror",
    category: "National",
    title: "Young Indians From Small Towns Losing Savings to Fake Work Permit Offers, Warn Immigration Experts",
    date: "14 Aug 2024",
    summary: "Legal experts issue crucial warnings regarding fraudulent overseas employment schemes, fake job offers, and essential document verification steps for aspiring international migrants.",
    link: "https://www.ahmedabadmirror.com/young-indians-from-small-towns-losing-savings-to-fake-work-permit-offers-warn-immigration-experts/81918948.html",
    featured: true,
    logoText: "Ahmedabad Mirror",
  },
  {
    id: "google-news",
    name: "Google News",
    category: "National",
    title: "Legal Commentary: Navigating Global Immigration Laws & Visa Refusal Appeals",
    date: "2024",
    summary: "Comprehensive coverage of immigration policy developments, student study permits, and legal remedies for visa rejections.",
    link: "https://news.google.com",
    featured: true,
    logoText: "Google News",
  },
  {
    id: "yahoo-news",
    name: "Yahoo! News",
    category: "National",
    title: "Understanding Overseas Employment Visa Scams & Safe Migration Pathways",
    date: "2024",
    summary: "Insights on how Indian professionals and students can verify international job offers and avoid common visa fraud pitfalls.",
    link: "https://news.yahoo.com",
    featured: true,
    logoText: "Yahoo! News",
  },
  {
    id: "india-today-times",
    name: "India Today Times",
    category: "Immigration",
    title: "Expert Advice on Permanent Residency Pathways for Skilled Indian Workers",
    date: "2024",
    summary: "Analysis of PR point systems, regional migration streams, and documentation compliance for Express Entry and PNP programs.",
    link: "#",
    featured: true,
    logoText: "India Today Times",
  },
  {
    id: "times-of-india-daily",
    name: "Times of India Daily",
    category: "Legal",
    title: "Bar Council Advocates Urge Due Diligence in Work Permit Applications",
    date: "2024",
    summary: "Key legal safeguards and documentation protocols recommended by seasoned immigration practitioners.",
    link: "#",
    featured: true,
    logoText: "TOI Daily",
  },
];

export const ALL_MEDIA_PUBLICATIONS: MediaItem[] = [
  ...FEATURED_ARTICLES,
  { id: "3", name: "India Global Live", category: "National", title: "Immigration Law Insights & Global Opportunities", link: "#" },
  { id: "4", name: "Indian Press Wire", category: "Legal", title: "Legal Rights of Overseas Visa Applicants", link: "#" },
  { id: "5", name: "Brief Buzz", category: "Immigration", title: "Student Visa Verification Guidelines", link: "#" },
  { id: "6", name: "Insightful News", category: "National", title: "Navigating Work Permit Compliance in 2024", link: "#" },
  { id: "7", name: "India Times Online", category: "National", title: "Avoiding Fraud in International Job Placements", link: "#" },
  { id: "8", name: "The India Watch", category: "Legal", title: "Understanding Legal Protections for Migrant Workers", link: "#" },
  { id: "9", name: "Village Voice News", category: "Regional", title: "Small Town Applicants Guidance on Visa Safety", link: "#" },
  { id: "10", name: "Karnataka News Network", category: "Regional", title: "Global Skilled Migration Trends", link: "#" },
  { id: "11", name: "Delhi News Daily", category: "National", title: "High Court & Tribunal Appeals for Visa Refusals", link: "#" },
  { id: "12", name: "Gossip Today", category: "Business", title: "Corporate Immigration & Sponsor Licenses", link: "#" },
  { id: "13", name: "Standard Today News", category: "National", title: "Family Sponsorship Visa Documentation", link: "#" },
  { id: "14", name: "Traveller News India", category: "Immigration", title: "Tourist vs Work Visa Rights Explained", link: "#" },
  { id: "15", name: "India Buzz News", category: "National", title: "Immigration Reforms & Skilled Migration", link: "#" },
  { id: "16", name: "Andhra News Digest", category: "Regional", title: "Protecting Overseas Job Seekers from Scams", link: "#" },
  { id: "17", name: "Latest News Today", category: "National", title: "Express Entry Draw Changes & Analysis", link: "#" },
  { id: "18", name: "India Latest News", category: "National", title: "Permanent Residency Verification Guide", link: "#" },
  { id: "19", name: "Latest News Himachal", category: "Regional", title: "Himachal Migrants Warning on Fake Permits", link: "#" },
  { id: "20", name: "India Live News Feed", category: "National", title: "Immigration Advocate Expert Perspective", link: "#" },
  { id: "21", name: "Indian Press Coverage", category: "Legal", title: "Legal Aspects of Overseas Contract Signing", link: "#" },
  { id: "22", name: "India Tribune Times", category: "National", title: "Work Permit Scam Awareness Report", link: "#" },
  { id: "23", name: "India Breaking Buzz", category: "Immigration", title: "Canada & UK Visa Policy Updates", link: "#" },
  { id: "24", name: "Newz Today 24", category: "National", title: "Verification Steps Before Paying Visa Agents", link: "#" },
  { id: "25", name: "News India Connectivity", category: "National", title: "Student Study Permit Rejection Remedies", link: "#" },
  { id: "26", name: "District Daily News", category: "Regional", title: "Grassroots Awareness on Visa Fraud", link: "#" },
  { id: "27", name: "Media Minds", category: "Business", title: "Global Talent Visas for Entrepreneurs", link: "#" },
  { id: "28", name: "News Indian Bulletin", category: "National", title: "Legal Consultation Importance in Visas", link: "#" },
  { id: "29", name: "Odisha News Hour", category: "Regional", title: "Safe International Relocation Protocols", link: "#" },
  { id: "30", name: "Quick News Now", category: "National", title: "Visa Refusal Appeal Timelines Explained", link: "#" },
  { id: "31", name: "India Brief Update", category: "National", title: "Immigration Lawyer Insights on Fraud Prevention", link: "#" },
  { id: "32", name: "India Press Dispatch", category: "Legal", title: "Bar Council Standards in Legal Representation", link: "#" },
  { id: "33", name: "Uttarakhand News Wire", category: "Regional", title: "Hill State Applicants Alert on Fake Visas", link: "#" },
  { id: "34", name: "Goa New Time", category: "Regional", title: "Tourist & Dependent Visa Legal Assistance", link: "#" },
  { id: "35", name: "India Bulletin News", category: "National", title: "Work Permit Rights & Contract Review", link: "#" },
  { id: "36", name: "India Wire News", category: "National", title: "Spouse & Family Sponsorship Pathways", link: "#" },
  { id: "37", name: "Indian Pulse Media", category: "National", title: "Youth Protection from Job Offer Scams", link: "#" },
  { id: "38", name: "India Mirror News", category: "National", title: "Verification of Employer Sponsor Licenses", link: "#" },
  { id: "39", name: "India Career Week", category: "Business", title: "Skilled Career Migration Guide 2024", link: "#" },
  { id: "40", name: "Buzz Center", category: "Immigration", title: "Immigration Policy Analysis & Advice", link: "#" },
  { id: "41", name: "India Bulletin Live", category: "National", title: "Legal Steps Following Visa Rejection", link: "#" },
  { id: "42", name: "Maharashtra Portal", category: "Regional", title: "Immigration Advisory for Overseas Job Seekers", link: "#" },
  { id: "43", name: "daily Street Journal", category: "Business", title: "Investor & Entrepreneur Visa Pathways", link: "#" },
  { id: "44", name: "Reach News", category: "National", title: "Public Awareness Drive on Visa Fraud", link: "#" },
  { id: "45", name: "Trend Stellers", category: "Immigration", title: "Top Immigration Destination Rules 2024", link: "#" },
  { id: "46", name: "India Buzz Feednews", category: "National", title: "Expert Legal Opinions on Visa Laws", link: "#" },
  { id: "47", name: "The Daily Glimpse", category: "National", title: "Key Red Flags in Fake Overseas Job Offers", link: "#" },
  { id: "48", name: "Gujarat Watch", category: "Regional", title: "Immigration Legal Help for Gujarati Families", link: "#" },
  { id: "49", name: "Indian Headline Buzz", category: "National", title: "Immigration Lawyer Guidance on Document Verification", link: "#" },
  { id: "50", name: "Jharkhand India News Agency", category: "Regional", title: "Eastern States Migration Awareness Campaign", link: "#" },
  { id: "51", name: "Rajasthan Headlines", category: "Regional", title: "Rajasthan Overseas Job Seekers Warning", link: "#" },
  { id: "52", name: "India Flash Bulletin", category: "National", title: "Legal Rights in Visa Appeals", link: "#" },
  { id: "53", name: "Express Times News", category: "National", title: "Understanding Points-Based Visa Systems", link: "#" },
  { id: "54", name: "The Indian Post", category: "National", title: "Immigration Fraud Prevention Initiative", link: "#" },
  { id: "55", name: "Indian News Daily Update", category: "National", title: "Permanent Residency Application Mistakes to Avoid", link: "#" },
  { id: "56", name: "The Quick Update", category: "National", title: "Fast-Track Visa Filing Guidelines", link: "#" },
  { id: "57", name: "News India Network", category: "National", title: "Legal Consultation for Overseas Migration", link: "#" },
  { id: "58", name: "Patrolling Wire News", category: "Legal", title: "Investigating Illegal Migration Rackets", link: "#" },
  { id: "59", name: "The Hindustan Express", category: "National", title: "Immigration Advocate Advocates Transparency", link: "#" },
  { id: "60", name: "Chronicle Today News", category: "National", title: "Work Visa Verification Procedures", link: "#" },
  { id: "61", name: "India Pulse Update", category: "National", title: "Immigration Trends & Legal Protections", link: "#" },
  { id: "62", name: "India Press Coverage", category: "Legal", title: "Legal Representation for Complex Visa Cases", link: "#" },
  { id: "63", name: "News India Web", category: "National", title: "Digital Verification of Visa Status", link: "#" },
  { id: "64", name: "Karnataka News Room", category: "Regional", title: "South India Tech Migration Legal Counsel", link: "#" },
  { id: "65", name: "Insider India Times", category: "National", title: "Immigration Attorney Explains PR Pathways", link: "#" },
  { id: "66", name: "India Briefings", category: "Business", title: "Global Corporate Mobility & Visas", link: "#" },
  { id: "67", name: "Daily Gossip Online", category: "National", title: "Public Education on Overseas Employment Scams", link: "#" },
  { id: "68", name: "News Wave India", category: "National", title: "Visa Refusal Overturn Strategies", link: "#" },
  { id: "69", name: "India News Junction", category: "National", title: "Safeguards for International Students", link: "#" },
  { id: "70", name: "Indian Daily Press", category: "National", title: "Legal Retainers in Immigration Law", link: "#" },
  { id: "71", name: "India Current Affairs", category: "National", title: "Immigration Policy Analysis & Legal Insights", link: "#" },
  { id: "72", name: "Tripura News Central", category: "Regional", title: "Northeast Migration Legal Awareness", link: "#" },
  { id: "73", name: "Report Today", category: "National", title: "Standard Operating Procedures in Visa Filing", link: "#" },
  { id: "74", name: "Story India", category: "National", title: "Success Stories in Overturned Visa Refusals", link: "#" },
  { id: "75", name: "India Today Updates", category: "National", title: "Key Updates on Express Entry & PNP", link: "#" },
  { id: "76", name: "India News Break", category: "National", title: "Exposing Fake Offer Letter Syndicates", link: "#" },
  { id: "77", name: "Indian News Channel", category: "National", title: "Immigration Lawyer Interview on Visa Fraud", link: "#" },
  { id: "78", name: "Daily India Updates", category: "National", title: "Verification Checklist for Aspirants", link: "#" },
  { id: "79", name: "Standard News Wire", category: "Legal", title: "Court Decrees & High Court Appeals in Visas", link: "#" },
  { id: "80", name: "India News Connect", category: "National", title: "Legal Rights for Overseas Candidates", link: "#" },
  { id: "81", name: "Business Line Print", category: "Business", title: "Investor Migration & Golden Visas", link: "#" },
  { id: "82", name: "Scroll India News", category: "National", title: "Immigration Reform Perspective", link: "#" },
  { id: "83", name: "Daily News India Online", category: "National", title: "Combating Unlicensed Migration Agents", link: "#" },
  { id: "84", name: "Madhya Pradesh News Tribune", category: "Regional", title: "Central India Aspirants Visa Caution", link: "#" },
  { id: "85", name: "News India Live", category: "National", title: "Live Legal Advice on Work Permits", link: "#" },
  { id: "86", name: "India Live News", category: "National", title: "Immigration Lawyer Urges Diligence", link: "#" },
  { id: "87", name: "Odisha News Voice", category: "Regional", title: "Regional Awareness on Fake Visas", link: "#" },
  { id: "88", name: "Nagaland News Watch", category: "Regional", title: "Northeast Skilled Migration Guidance", link: "#" },
  { id: "89", name: "News India Point", category: "National", title: "Essential Documents for Study Permits", link: "#" },
  { id: "90", name: "Telangana News Spot", category: "Regional", title: "Hyderabad Tech Migration Legal Tips", link: "#" },
  { id: "91", name: "India News Nation", category: "National", title: "National Drive Against Job Rackets", link: "#" },
  { id: "92", name: "The India Talks", category: "National", title: "Legal Discussion on Citizenship Laws", link: "#" },
  { id: "93", name: "India Flashnewsfeed", category: "National", title: "Breaking News in Overseas Visa Regulations", link: "#" },
  { id: "94", name: "Tech Times News", category: "Business", title: "Tech Professional Visas & H-1B / O-1 Pathways", link: "#" },
  { id: "95", name: "India Buzz Times", category: "National", title: "Immigration Advocate Fraud Warning", link: "#" },
  { id: "96", name: "India Reporter Live", category: "National", title: "Investigative Report on Work Visa Scams", link: "#" },
  { id: "97", name: "Punjab News Network", category: "Regional", title: "Punjab Youth Protection from Illegal Agents", link: "#" },
  { id: "98", name: "News India Times", category: "National", title: "Legal Obligations of Immigration Lawyers", link: "#" },
  { id: "99", name: "India Press Buzz", category: "Legal", title: "Bar Council Advocacy in Legal Ethics", link: "#" },
  { id: "100", name: "The Report Net", category: "National", title: "In-Depth Analysis of Overseas Migration Laws", link: "#" },
];
