export interface MediaItem {
  id: string;
  name: string;
  category: "National" | "Regional" | "Business" | "Legal" | "Immigration";
  title: string;
  date?: string;
  summary?: string;
  link: string;
  featured?: boolean;
  logoText?: string;
  img?: string;
  accentColor?: string;
}

export const FEATURED_ARTICLES: MediaItem[] = [
  {
    id: "tribune-india",
    name: "The Tribune",
    category: "National",
    title: "Immigration Experts Highlight Fraud Risks Linked to Fake Work Permit Offers in India",
    date: "14 Aug 2024",
    summary: "Every week, families from small towns across Punjab, Haryana, Uttar Pradesh, Himachal Pradesh and several other states make one of the biggest financial decisions of their lives — navigating fake work permit risks with guidance from expert immigration advocates.",
    link: "https://www.tribuneindia.com/partner-exclusives/immigration-experts-highlight-fraud-risks-linked-to-fake-work-permit-offers-in-india/",
    featured: true,
    logoText: "The Tribune",
    img: "/images/tribune_coverage.jpg",
    accentColor: "from-red-600 to-rose-700",
  },
  {
    id: "ahmedabad-mirror",
    name: "Ahmedabad Mirror",
    category: "National",
    title: "Young Indians From Small Towns Losing Savings to Fake Work Permit Offers, Warn Immigration Experts",
    date: "14 Aug 2024",
    summary: "Legal experts issue crucial warnings regarding fraudulent overseas employment schemes, fake job offers, and essential document verification steps for aspiring international migrants.",
    link: "https://www.ahmedabadmirror.com/young-indians-from-small-towns-losing-savings-to-fake-work-permit-offers-warn-immigration-experts/81918948.html",
    featured: true,
    logoText: "Ahmedabad Mirror",
    img: "/images/ahmedabad_coverage.jpg",
    accentColor: "from-amber-500 to-orange-600",
  },
  {
    id: "google-news",
    name: "Google News",
    category: "National",
    title: "Legal Commentary: Navigating Global Immigration Laws & Visa Refusal Appeals",
    date: "2024",
    summary: "Comprehensive coverage of immigration policy developments, student study permits, and legal remedies for visa rejections.",
    link: "https://news.google.com/search?q=Advocate+Richa+Dhanda+Immigration",
    featured: true,
    logoText: "Google News",
    img: "/images/consultation.jpg",
    accentColor: "from-blue-600 to-indigo-700",
  },
  {
    id: "yahoo-news",
    name: "Yahoo! News",
    category: "National",
    title: "Understanding Overseas Employment Visa Scams & Safe Migration Pathways",
    date: "2024",
    summary: "Insights on how Indian professionals and students can verify international job offers and avoid common visa fraud pitfalls.",
    link: "https://news.search.yahoo.com/search?p=Advocate+Richa+Dhanda",
    featured: true,
    logoText: "Yahoo! News",
    img: "/images/business.jpg",
    accentColor: "from-purple-600 to-violet-700",
  },
  {
    id: "india-today-times",
    name: "India Today Times",
    category: "Immigration",
    title: "Expert Advice on Permanent Residency Pathways for Skilled Indian Workers",
    date: "2024",
    summary: "Analysis of PR point systems, regional migration streams, and documentation compliance for Express Entry and PNP programs.",
    link: "https://news.google.com/search?q=India+Today+Advocate+Richa+Dhanda",
    featured: true,
    logoText: "India Today Times",
    img: "/images/pr.jpg",
    accentColor: "from-emerald-600 to-teal-700",
  },
  {
    id: "times-of-india-daily",
    name: "Times of India Daily",
    category: "Legal",
    title: "Bar Council Advocates Urge Due Diligence in Work Permit Applications",
    date: "2024",
    summary: "Key legal safeguards and documentation protocols recommended by seasoned immigration practitioners.",
    link: "https://news.google.com/search?q=Times+of+India+Advocate+Richa+Dhanda",
    featured: true,
    logoText: "TOI Daily",
    img: "/images/appeals.jpg",
    accentColor: "from-amber-600 to-yellow-600",
  },
];

const getNewsLink = (name: string) =>
  `https://news.google.com/search?q=${encodeURIComponent(name + " Advocate Richa Dhanda Immigration")}`;

export const ALL_MEDIA_PUBLICATIONS: MediaItem[] = [
  ...FEATURED_ARTICLES,
  { id: "3", name: "India Global Live", category: "National", title: "Immigration Law Insights & Global Opportunities", link: getNewsLink("India Global Live"), img: "/images/business.jpg" },
  { id: "4", name: "Indian Press Wire", category: "Legal", title: "Legal Rights of Overseas Visa Applicants", link: getNewsLink("Indian Press Wire"), img: "/images/appeals.jpg" },
  { id: "5", name: "Brief Buzz", category: "Immigration", title: "Student Visa Verification Guidelines", link: getNewsLink("Brief Buzz"), img: "/images/tourist.jpg" },
  { id: "6", name: "Insightful News", category: "National", title: "Navigating Work Permit Compliance in 2024", link: getNewsLink("Insightful News"), img: "/images/pr.jpg" },
  { id: "7", name: "India Times Online", category: "National", title: "Avoiding Fraud in International Job Placements", link: getNewsLink("India Times Online"), img: "/images/consultation.jpg" },
  { id: "8", name: "The India Watch", category: "Legal", title: "Understanding Legal Protections for Migrant Workers", link: getNewsLink("The India Watch"), img: "/images/citizenship.jpg" },
  { id: "9", name: "Village Voice News", category: "Regional", title: "Small Town Applicants Guidance on Visa Safety", link: getNewsLink("Village Voice News"), img: "/images/family.jpg" },
  { id: "10", name: "Karnataka News Network", category: "Regional", title: "Global Skilled Migration Trends", link: getNewsLink("Karnataka News Network"), img: "/images/business.jpg" },
  { id: "11", name: "Delhi News Daily", category: "National", title: "High Court & Tribunal Appeals for Visa Refusals", link: getNewsLink("Delhi News Daily"), img: "/images/appeals.jpg" },
  { id: "12", name: "Gossip Today", category: "Business", title: "Corporate Immigration & Sponsor Licenses", link: getNewsLink("Gossip Today"), img: "/images/business.jpg" },
  { id: "13", name: "Standard Today News", category: "National", title: "Family Sponsorship Visa Documentation", link: getNewsLink("Standard Today News"), img: "/images/family.jpg" },
  { id: "14", name: "Traveller News India", category: "Immigration", title: "Tourist vs Work Visa Rights Explained", link: getNewsLink("Traveller News India"), img: "/images/tourist.jpg" },
  { id: "15", name: "India Buzz News", category: "National", title: "Immigration Reforms & Skilled Migration", link: getNewsLink("India Buzz News"), img: "/images/pr.jpg" },
  { id: "16", name: "Andhra News Digest", category: "Regional", title: "Protecting Overseas Job Seekers from Scams", link: getNewsLink("Andhra News Digest"), img: "/images/consultation.jpg" },
  { id: "17", name: "Latest News Today", category: "National", title: "Express Entry Draw Changes & Analysis", link: getNewsLink("Latest News Today"), img: "/images/citizenship.jpg" },
  { id: "18", name: "India Latest News", category: "National", title: "Permanent Residency Verification Guide", link: getNewsLink("India Latest News"), img: "/images/pr.jpg" },
  { id: "19", name: "Latest News Himachal", category: "Regional", title: "Himachal Migrants Warning on Fake Permits", link: getNewsLink("Latest News Himachal"), img: "/images/appeals.jpg" },
  { id: "20", name: "India Live News Feed", category: "National", title: "Immigration Advocate Expert Perspective", link: getNewsLink("India Live News Feed"), img: "/images/consultation.jpg" },
  { id: "21", name: "Indian Press Coverage", category: "Legal", title: "Legal Aspects of Overseas Contract Signing", link: getNewsLink("Indian Press Coverage"), img: "/images/business.jpg" },
  { id: "22", name: "India Tribune Times", category: "National", title: "Work Permit Scam Awareness Report", link: "https://www.tribuneindia.com/partner-exclusives/immigration-experts-highlight-fraud-risks-linked-to-fake-work-permit-offers-in-india/", img: "/images/tribune_coverage.jpg" },
  { id: "23", name: "India Breaking Buzz", category: "Immigration", title: "Canada & UK Visa Policy Updates", link: getNewsLink("India Breaking Buzz"), img: "/images/pr.jpg" },
  { id: "24", name: "Newz Today 24", category: "National", title: "Verification Steps Before Paying Visa Agents", link: "https://www.ahmedabadmirror.com/young-indians-from-small-towns-losing-savings-to-fake-work-permit-offers-warn-immigration-experts/81918948.html", img: "/images/ahmedabad_coverage.jpg" },
  { id: "25", name: "News India Connectivity", category: "National", title: "Student Study Permit Rejection Remedies", link: getNewsLink("News India Connectivity"), img: "/images/tourist.jpg" },
  { id: "26", name: "District Daily News", category: "Regional", title: "Grassroots Awareness on Visa Fraud", link: getNewsLink("District Daily News"), img: "/images/family.jpg" },
  { id: "27", name: "Media Minds", category: "Business", title: "Global Talent Visas for Entrepreneurs", link: getNewsLink("Media Minds"), img: "/images/business.jpg" },
  { id: "28", name: "News Indian Bulletin", category: "National", title: "Legal Consultation Importance in Visas", link: getNewsLink("News Indian Bulletin"), img: "/images/consultation.jpg" },
  { id: "29", name: "Odisha News Hour", category: "Regional", title: "Safe International Relocation Protocols", link: getNewsLink("Odisha News Hour"), img: "/images/pr.jpg" },
  { id: "30", name: "Quick News Now", category: "National", title: "Visa Refusal Appeal Timelines Explained", link: getNewsLink("Quick News Now"), img: "/images/appeals.jpg" },
  { id: "31", name: "India Brief Update", category: "National", title: "Immigration Lawyer Insights on Fraud Prevention", link: getNewsLink("India Brief Update"), img: "/images/consultation.jpg" },
  { id: "32", name: "India Press Dispatch", category: "Legal", title: "Bar Council Standards in Legal Representation", link: getNewsLink("India Press Dispatch"), img: "/images/citizenship.jpg" },
  { id: "33", name: "Uttarakhand News Wire", category: "Regional", title: "Hill State Applicants Alert on Fake Visas", link: getNewsLink("Uttarakhand News Wire"), img: "/images/appeals.jpg" },
  { id: "34", name: "Goa New Time", category: "Regional", title: "Tourist & Dependent Visa Legal Assistance", link: getNewsLink("Goa New Time"), img: "/images/tourist.jpg" },
  { id: "35", name: "India Bulletin News", category: "National", title: "Work Permit Rights & Contract Review", link: getNewsLink("India Bulletin News"), img: "/images/business.jpg" },
  { id: "36", name: "India Wire News", category: "National", title: "Spouse & Family Sponsorship Pathways", link: getNewsLink("India Wire News"), img: "/images/family.jpg" },
  { id: "37", name: "Indian Pulse Media", category: "National", title: "Youth Protection from Job Offer Scams", link: "https://www.ahmedabadmirror.com/young-indians-from-small-towns-losing-savings-to-fake-work-permit-offers-warn-immigration-experts/81918948.html", img: "/images/ahmedabad_coverage.jpg" },
  { id: "38", name: "India Mirror News", category: "National", title: "Verification of Employer Sponsor Licenses", link: getNewsLink("India Mirror News"), img: "/images/business.jpg" },
  { id: "39", name: "India Career Week", category: "Business", title: "Skilled Career Migration Guide 2024", link: getNewsLink("India Career Week"), img: "/images/business.jpg" },
  { id: "40", name: "Buzz Center", category: "Immigration", title: "Immigration Policy Analysis & Advice", link: getNewsLink("Buzz Center"), img: "/images/pr.jpg" },
  { id: "41", name: "India Bulletin Live", category: "National", title: "Legal Steps Following Visa Rejection", link: getNewsLink("India Bulletin Live"), img: "/images/appeals.jpg" },
  { id: "42", name: "Maharashtra Portal", category: "Regional", title: "Immigration Advisory for Overseas Job Seekers", link: getNewsLink("Maharashtra Portal"), img: "/images/consultation.jpg" },
  { id: "43", name: "daily Street Journal", category: "Business", title: "Investor & Entrepreneur Visa Pathways", link: getNewsLink("daily Street Journal"), img: "/images/business.jpg" },
  { id: "44", name: "Reach News", category: "National", title: "Public Awareness Drive on Visa Fraud", link: "https://www.tribuneindia.com/partner-exclusives/immigration-experts-highlight-fraud-risks-linked-to-fake-work-permit-offers-in-india/", img: "/images/tribune_coverage.jpg" },
  { id: "45", name: "Trend Stellers", category: "Immigration", title: "Top Immigration Destination Rules 2024", link: getNewsLink("Trend Stellers"), img: "/images/pr.jpg" },
  { id: "46", name: "India Buzz Feednews", category: "National", title: "Expert Legal Opinions on Visa Laws", link: getNewsLink("India Buzz Feednews"), img: "/images/consultation.jpg" },
  { id: "47", name: "The Daily Glimpse", category: "National", title: "Key Red Flags in Fake Overseas Job Offers", link: "https://www.ahmedabadmirror.com/young-indians-from-small-towns-losing-savings-to-fake-work-permit-offers-warn-immigration-experts/81918948.html", img: "/images/ahmedabad_coverage.jpg" },
  { id: "48", name: "Gujarat Watch", category: "Regional", title: "Immigration Legal Help for Gujarati Families", link: getNewsLink("Gujarat Watch"), img: "/images/family.jpg" },
  { id: "49", name: "Indian Headline Buzz", category: "National", title: "Immigration Lawyer Guidance on Document Verification", link: getNewsLink("Indian Headline Buzz"), img: "/images/business.jpg" },
  { id: "50", name: "Jharkhand India News Agency", category: "Regional", title: "Eastern States Migration Awareness Campaign", link: getNewsLink("Jharkhand India News Agency"), img: "/images/consultation.jpg" },
];
